# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96acf2f72fc03c90c45b320a813fe5aaba848fe13789c51f187956cb081514d75895d42c03579bb04a629502ce31fb7afb278796ea5765f2365f36a3f1effb7a

test:
  secret_key_base: 5e0704cb06565dc4e56d3efcd5726a849246687d5ac35a9797ea68b121e941cecd72130b248008a0da7cd00efa74b7dffb45ad30119f23d60d21f1b8f69ebb44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
